CREATE SEQUENCE ACCOUNT_TYPE_SEQ
    START WITH 10000
    INCREMENT BY 1
    MINVALUE 1
    NOCYCLE
    CACHE 20
    NOORDER;
CREATE TABLE ACCOUNT_TYPE (
    ACCOUNT_TYPE_ID NUMBER(15) NOT NULL,
    MNEMONIC VARCHAR2(50) NOT NULL,
    ACCOUNT_TYPE_NAME VARCHAR2(50) NOT NULL,
    CREATION_DATE DATE NOT NULL,
    CONSTRAINT ACCOUNT_TYPE_PK PRIMARY KEY (ACCOUNT_TYPE_ID)
);

CREATE SEQUENCE ACCOUNT_TX_SEQ
    START WITH 10000
    INCREMENT BY 1
    MINVALUE 1
    NOCYCLE
    CACHE 20
    NOORDER;
CREATE TABLE ACCOUNT_TX (
    ACCOUNT_TX_ID NUMBER(15) NOT NULL,
    ACCOUNT_TYPE_ID NUMBER(15) NOT NULL,
    MEMBER_ID NUMBER(15) NOT NULL,
    AMOUNT NUMBER(4) NOT NULL,
    TX_DATE DATE NOT NULL,
    CONSTRAINT ACCOUNT_TX_PK PRIMARY KEY (ACCOUNT_TX_ID),
    CONSTRAINT fk_Type FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE(ACCOUNT_TYPE_ID)
);

CREATE SEQUENCE ACCOUNT_TX_DETAILS_SEQ
    START WITH 10000
    INCREMENT BY 1
    MINVALUE 1
    NOCYCLE
    CACHE 20
    NOORDER;
Create TABLE  ACCOUNT_TX_DETAILS(
    ACCOUNT_TX_DETAILS_ID NUMBER(15) NOT NULL,
    ACCOUNT_TX_ID NUMBER(15)NOT NULL,
    PARTNER_NAME VARCHAR2(255) NOT NULL,
    NUMBER_OF_ITEMS INT NOT NULL,
    PRIMARY KEY (ACCOUNT_TX_DETAILS_ID),
    CONSTRAINT FK_TX_DETAILS FOREIGN KEY (ACCOUNT_TX_ID) REFERENCES ACCOUNT_TX(ACCOUNT_TX_ID)
);
